title: SANTANASMART
description: Un blog simple hecho con Jekyll
author: Juan Pérez
email: ejemplo@email.com
baseurl: "" # si es tuusuario.github.io
url: "https://tuusuario.github.io"

theme: minima
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
