title: SantanaSmart
description: Empresa de asesoría industrial especializada en apoyar a startups y empresas consolidadas del parque empresarial de Linares. Innovación, eficiencia y desarrollo tecnológico.
keywords: asesoría industrial, parque empresarial Linares, industria, automatización, empresas tecnológicas, ingeniería, eficiencia industrial
author:
  name: SantanaSmart
  email: santanasmart@proton.me
  twitter: santanasmart
url: "https://www.santanasmart.com"
image: /assets/img/logo.jpg
